import { Header } from '@/components/header/header';
import type { Metadata } from 'next';
import './globals.css';
import { Footer } from '@/components/footer/footer';
import Head from 'next/head';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body>
        <Header />
        <main>{children}</main>
        <Footer />
        <script
          src='https://cdn.pulse.is/livechat/loader.js'
          data-live-chat-id='66bb66388f0e7d21950b076b'
          async></script>
      </body>
    </html>
  );
}
